-- Auto-generated: register solutions + test files
BEGIN;
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\1\mainSolution\solution.cpp' WHERE id = 1;
DELETE FROM test_files WHERE problem_id = 1;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\1\tests\1_in.txt', 1);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\1\tests\2_in.txt', 1);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\1\tests\3_in.txt', 1);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\1\tests\4_in.txt', 1);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\1\tests\5_in.txt', 1);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\2\mainSolution\solution.cpp' WHERE id = 2;
DELETE FROM test_files WHERE problem_id = 2;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\2\tests\1_in.txt', 2);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\2\tests\2_in.txt', 2);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\2\tests\3_in.txt', 2);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\2\tests\4_in.txt', 2);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\2\tests\5_in.txt', 2);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (6, '6_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\2\tests\6_in.txt', 2);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\3\mainSolution\solution.cpp' WHERE id = 3;
DELETE FROM test_files WHERE problem_id = 3;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\3\tests\1_in.txt', 3);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\3\tests\2_in.txt', 3);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\3\tests\3_in.txt', 3);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\3\tests\4_in.txt', 3);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\3\tests\5_in.txt', 3);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (6, '6_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\3\tests\6_in.txt', 3);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\4\mainSolution\solution.cpp' WHERE id = 4;
DELETE FROM test_files WHERE problem_id = 4;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\4\tests\1_in.txt', 4);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\4\tests\2_in.txt', 4);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\4\tests\3_in.txt', 4);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\4\tests\4_in.txt', 4);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\4\tests\5_in.txt', 4);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (6, '6_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\4\tests\6_in.txt', 4);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\5\mainSolution\solution.cpp' WHERE id = 5;
DELETE FROM test_files WHERE problem_id = 5;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\5\tests\1_in.txt', 5);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\5\tests\2_in.txt', 5);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\5\tests\3_in.txt', 5);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\5\tests\4_in.txt', 5);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\5\tests\5_in.txt', 5);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\6\mainSolution\solution.cpp' WHERE id = 6;
DELETE FROM test_files WHERE problem_id = 6;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\6\tests\1_in.txt', 6);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\6\tests\2_in.txt', 6);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\6\tests\3_in.txt', 6);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\6\tests\4_in.txt', 6);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\6\tests\5_in.txt', 6);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\7\mainSolution\solution.cpp' WHERE id = 7;
DELETE FROM test_files WHERE problem_id = 7;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\7\tests\1_in.txt', 7);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\7\tests\2_in.txt', 7);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\7\tests\3_in.txt', 7);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\7\tests\4_in.txt', 7);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\7\tests\5_in.txt', 7);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\8\mainSolution\solution.cpp' WHERE id = 8;
DELETE FROM test_files WHERE problem_id = 8;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\8\tests\1_in.txt', 8);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\8\tests\2_in.txt', 8);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\8\tests\3_in.txt', 8);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\8\tests\4_in.txt', 8);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\8\tests\5_in.txt', 8);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (6, '6_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\8\tests\6_in.txt', 8);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\9\mainSolution\solution.cpp' WHERE id = 9;
DELETE FROM test_files WHERE problem_id = 9;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\9\tests\1_in.txt', 9);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\9\tests\2_in.txt', 9);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\9\tests\3_in.txt', 9);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\9\tests\4_in.txt', 9);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\9\tests\5_in.txt', 9);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\10\mainSolution\solution.cpp' WHERE id = 10;
DELETE FROM test_files WHERE problem_id = 10;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\10\tests\1_in.txt', 10);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\10\tests\2_in.txt', 10);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\10\tests\3_in.txt', 10);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\10\tests\4_in.txt', 10);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\10\tests\5_in.txt', 10);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (6, '6_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\10\tests\6_in.txt', 10);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\11\mainSolution\solution.cpp' WHERE id = 11;
DELETE FROM test_files WHERE problem_id = 11;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\11\tests\1_in.txt', 11);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\11\tests\2_in.txt', 11);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\11\tests\3_in.txt', 11);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\11\tests\4_in.txt', 11);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\11\tests\5_in.txt', 11);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (6, '6_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\11\tests\6_in.txt', 11);
UPDATE problems SET main_solution_path = 'c:\Users\User\Desktop\XOROJ\uploads\problems\12\mainSolution\solution.cpp' WHERE id = 12;
DELETE FROM test_files WHERE problem_id = 12;
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (1, '1_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\12\tests\1_in.txt', 12);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (2, '2_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\12\tests\2_in.txt', 12);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (3, '3_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\12\tests\3_in.txt', 12);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (4, '4_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\12\tests\4_in.txt', 12);
INSERT INTO test_files (test_id, file_name, file_path, problem_id) VALUES (5, '5_in.txt', 'c:\Users\User\Desktop\XOROJ\uploads\problems\12\tests\5_in.txt', 12);
COMMIT;
